### PR TITLE
Typo error fix

### PR DESCRIPTION
**Pull request by sem1colon**
Plugin name is case-sensitive.

### CODE REVIEW

**Comment by Dumluregn** [comment]
Hello, this is not a plugin name, but a button name and this is a naming convention we are using in CKEditor.

**Comment by sem1colon** [comment]
But this won't work when trying with Angular. I've checked.

**Comment by Dumluregn** [comment]
Then it must be connected with the way you are implementing it - all other plugins have the same convention and our [Angular integration](https://github.com/ckeditor/ckeditor4-angular) is working fine.

**Comment by sem1colon** [comment]
Okay, I tied with ng2-ckeditor which is built upon ckeditor4. There it's case sensitive. I request you to verify again.

**Comment by Dumluregn** [comment]
Sorry, but we are not the authors of `ng2-ckeditor` package, therefore we don't guarantee it will be working correctly.

**Pull request closed without merging**
